#!/usr/bin/env python3
import json
import re
import sys
from google_trans_new import google_translator

# Force UTF-8 output on Windows
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

translator = google_translator()

def extract_english_text(text_file):
    """Load and parse the English text.js file"""
    with open(text_file, 'r', encoding='utf-8') as f:
        content = f.read()

    match = re.search(r'const RAMAYANA_TEXT\s*=\s*(\[.*\]);?\s*$', content, re.DOTALL)
    if match:
        json_str = match.group(1)
    else:
        json_str = content.replace('const RAMAYANA_TEXT=', '').rstrip(';').strip()
    
    return json.loads(json_str)

def translate_paragraph(text, retries=3):
    """Translate a paragraph to Hebrew"""
    if not text or not text.strip():
        return text
    
    for attempt in range(retries):
        try:
            result = translator.translate(text, lang_src='en', lang_tgt='he')
            return result if result else text
        except Exception as e:
            if attempt == retries - 1:
                return text
    return text

def translate_structure(data, depth=0):
    """Recursively translate text"""
    if isinstance(data, dict):
        translated = {}
        for key, value in data.items():
            if key == 'subtitle' and isinstance(value, str):
                translated[key] = translate_paragraph(value)
            elif key == 'title' and isinstance(value, str):
                if value and ord(value[0]) < 128:
                    translated[key] = translate_paragraph(value)
                else:
                    translated[key] = value
            elif key == 'paragraphs' and isinstance(value, list):
                translated[key] = []
                print(f"Translating {len(value)} paragraphs...")
                for i, para in enumerate(value):
                    trans_para = translate_paragraph(para)
                    translated[key].append(trans_para)
                    if (i + 1) % 10 == 0:
                        print(f"  Progress: {i+1}/{len(value)}")
            else:
                translated[key] = translate_structure(value, depth + 1)
        return translated
    elif isinstance(data, list):
        return [translate_structure(item, depth) for item in data]
    else:
        return data

def main():
    en_file = r'C:\Users\Main\OneDrive\Documents\Neta\ramayana-site\data\text.js'
    he_file = r'C:\Users\Main\OneDrive\Documents\Neta\ramayana-site\data\text_he.js'

    print("Loading English Ramayana text...")
    data = extract_english_text(en_file)
    print(f"Loaded {len(data)} books\n")

    print("Translating to Hebrew (5-10 minutes)...\n")
    hebrew_data = translate_structure(data)

    print("\nSaving Hebrew translation...")
    with open(he_file, 'w', encoding='utf-8') as f:
        f.write('// auto-generated by translate_to_hebrew.py\n')
        f.write('const RAMAYANA_TEXT_HE=')
        f.write(json.dumps(hebrew_data, ensure_ascii=False, indent=2))
        f.write(';')

    print(f"DONE! Saved to {he_file}")
    print("Refresh your browser and switch to Hebrew!")

if __name__ == '__main__':
    main()
