#!/usr/bin/env python3
"""
Comprehensive translation of ALL website content to Hebrew using Google Cloud Translation API
Translates:
1. All 7 books' verses (text.js -> text_he.js)
2. All commentary (commentary.js -> commentary_he.js)
3. All UI strings (site.js STRINGS -> strings_he.json)
"""

import json
import time
import sys
import requests
from pathlib import Path

API_KEY = "REDACTED_GOOGLE_API_KEY"
API_ENDPOINT = "https://translation.googleapis.com/language/translate/v2"

def translate_text(text):
    """Translate single text to Hebrew using Google Cloud Translation API"""
    if not text or not isinstance(text, str):
        return text

    if len(text.strip()) == 0:
        return text

    try:
        response = requests.post(
            API_ENDPOINT,
            params={
                'key': API_KEY,
                'source_language': 'en',
                'target_language': 'he',
                'q': text
            },
            timeout=30
        )

        if response.status_code == 200:
            data = response.json()
            if 'data' in data and 'translations' in data['data']:
                translated = data['data']['translations'][0]['translatedText']
                return translated
        else:
            print(f"    [ERROR] HTTP {response.status_code}: {response.text[:100]}")
            return text
    except Exception as e:
        print(f"    [ERROR] {str(e)[:80]}")
        return text

print("\n" + "="*70)
print("COMPREHENSIVE HEBREW TRANSLATION - ALL WEBSITE CONTENT")
print("="*70)

# ============================================================================
# PART 1: TRANSLATE VERSES (text.js -> text_he.js)
# ============================================================================
print("\n[PART 1/3] Translating all 7 books' verses...")

with open('data/text.js', 'r', encoding='utf-8') as f:
    content = f.read()
    start = content.find('[')
    end = content.rfind(']') + 1
    books_en = json.loads(content[start:end])

print(f"  Loaded {len(books_en)} books")

books_he = []
for book_idx, book in enumerate(books_en, 1):
    book_num = book.get('number', '?')
    print(f"\n  Book {book_num}: Translating title and {len(book.get('cantos', []))} cantos...")

    book_he = {
        'number': book.get('number'),
        'title': translate_text(book.get('title', '')),
        'subtitle': translate_text(book.get('subtitle', '')),
        'headerImage': book.get('headerImage'),
        'cantos': []
    }

    for canto_idx, canto in enumerate(book.get('cantos', [])):
        if (canto_idx + 1) % 10 == 0 or canto_idx == 0:
            print(f"    Canto {canto_idx + 1}/{len(book.get('cantos', []))}")

        canto_he = {
            'number': canto.get('number'),
            'title': translate_text(canto.get('title', '')),
            'paragraphs': []
        }

        for para in canto.get('paragraphs', []):
            translated_para = translate_text(para)
            canto_he['paragraphs'].append(translated_para)
            time.sleep(0.1)  # Small delay to avoid rate limiting

        book_he['cantos'].append(canto_he)

    books_he.append(book_he)
    print(f"  [OK] Book {book_num} translated")

# Save translated verses
output_file = "data/text_he.js"
output_content = f"// auto-generated by Google Cloud Translation API\nconst RAMAYANA_TEXT_HE={json.dumps(books_he, ensure_ascii=False, indent=2)};"
with open(output_file, 'w', encoding='utf-8') as f:
    f.write(output_content)

file_size = len(output_content) / 1024 / 1024
print(f"\n[PART 1 COMPLETE] Saved {output_file} ({file_size:.2f} MB)")

# ============================================================================
# PART 2: TRANSLATE COMMENTARY (commentary.js -> commentary_he.js)
# ============================================================================
print("\n[PART 2/3] Translating all commentary...")

with open('data/commentary.js', 'r', encoding='utf-8') as f:
    content = f.read()
    start = content.find('[')
    end = content.rfind(']') + 1
    commentary_en = json.loads(content[start:end])

def translate_commentary_recursive(obj):
    """Recursively translate text/intro/keyIdea fields in commentary"""
    if isinstance(obj, dict):
        result = {}
        for key, value in obj.items():
            if key in ['text', 'intro', 'keyIdea'] and isinstance(value, str):
                result[key] = translate_text(value)
                time.sleep(0.1)
            elif isinstance(value, (dict, list)):
                result[key] = translate_commentary_recursive(value)
            else:
                result[key] = value
        return result
    elif isinstance(obj, list):
        return [translate_commentary_recursive(item) for item in obj]
    else:
        return obj

print(f"  Loaded {len(commentary_en)} books of commentary")
commentary_he = translate_commentary_recursive(commentary_en)

output_file = "data/commentary_he.js"
output_content = f"// auto-generated by Google Cloud Translation API\nconst RAMAYANA_COMMENTARY_HE={json.dumps(commentary_he, ensure_ascii=False, indent=2)};"
with open(output_file, 'w', encoding='utf-8') as f:
    f.write(output_content)

file_size = len(output_content) / 1024 / 1024
print(f"[PART 2 COMPLETE] Saved {output_file} ({file_size:.2f} MB)")

# ============================================================================
# PART 3: TRANSLATE UI STRINGS (site.js STRINGS object)
# ============================================================================
print("\n[PART 3/3] Translating all UI strings...")

# Extract STRINGS from site.js manually (it's JavaScript, not JSON)
with open('site.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the STRINGS object boundaries
start_idx = content.find('var STRINGS = {')
end_idx = content.find('};', start_idx) + 2

if start_idx > 0 and end_idx > start_idx:
    strings_section = content[start_idx + len('var STRINGS = '):end_idx]
    try:
        # Try to parse as JSON (with some cleanup for JS-specific syntax)
        strings_section_clean = strings_section.replace("'", '"').replace('true', 'true').replace('false', 'false')
        original_strings = json.loads(strings_section_clean)
    except:
        print("  [WARNING] Could not parse STRINGS object, trying manual extraction...")
        original_strings = {}

# Translate each English string
strings_he = {}
if 'en' in original_strings:
    print(f"  Found {len(original_strings['en'])} UI strings to translate")
    for key, value in original_strings['en'].items():
        if isinstance(value, str) and not key.startswith('footer'):  # Skip HTML footer
            strings_he[key] = translate_text(value)
            time.sleep(0.1)
        else:
            strings_he[key] = value
else:
    print("  [WARNING] Could not find 'en' strings, skipping UI translation")

# Save as JSON file for reference
output_file = "data/strings_he.json"
with open(output_file, 'w', encoding='utf-8') as f:
    json.dump(strings_he, f, ensure_ascii=False, indent=2)

print(f"[PART 3 COMPLETE] Saved {output_file}")

# ============================================================================
# FINAL SUMMARY
# ============================================================================
print("\n" + "="*70)
print("[SUCCESS] COMPREHENSIVE TRANSLATION COMPLETE!")
print("="*70)
print(f"\nTranslated files created:")
print(f"  1. data/text_he.js          - All 7 books' verses ({len(books_he)} books, {sum(len(b['cantos']) for b in books_he)} cantos)")
print(f"  2. data/commentary_he.js    - All commentary")
print(f"  3. data/strings_he.json     - All UI strings")
print(f"\nRefresh your browser (Ctrl+Shift+R for hard refresh)")
print(f"Then toggle to Hebrew to see all translations!")
print("\n")
