#!/usr/bin/env python3
import json
import os
import sys

# Import from the site's script
sys.path.insert(0, os.path.dirname(__file__))

from translate_to_hebrew import translate_paragraphs
import anthropic

# Get API key
api_key = os.environ.get('ANTHROPIC_API_KEY')
if not api_key:
    print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
    sys.exit(1)

client = anthropic.Anthropic(api_key=api_key)

# Canto data with English paragraphs
cantos = [
    {
        "number": "LXII",
        "title": "Ambarísha's Sacrifice",
        "paragraphs": [
            "As thus the king that youth conveyed,\nHis weary steeds at length he stayed\nAt height of noon their rest to take\nUpon the bank of Pushkar's lake.\nThere while the king enjoyed repose\nThe captive Śunahśepha rose,\nAnd hasting to the water's side\nHis uncle Viśvámitra spied,\nWith many a hermit 'neath the trees\nEngaged in stern austerities.",
            "Distracted with the toil and thirst,\nWith woeful mien, away he burst,\nSwift to the hermit's breast he flew,\nAnd weeping thus began to sue:\n\"No sire have I, no mother dear,\nNo kith or kin my heart to cheer:\nAs justice bids, O Hermit, deign\nTo save me from the threatened pain.\nO thou to whom the wretched flee,\nAnd find a saviour, Saint, in thee,\nNow let the king obtain his will,\nAnd me my length of days fulfil,\nThat rites austere I too may share,\nMay rise to heaven and rest me there.\nWith tender soul and gentle brow\nBe guardian of the orphan thou,\nAnd as a father pities, so\nPreserve me from my fear and woe.\"",
            "When Viśvámitra, glorious saint,\nHad heard the boy's heart-rending plaint.\nHe soothed his grief, his tears he dried,\nThen called his sons to him, and cried:\n\"The time is come for you to show\nThe duty and the aid bestow\nFor which, regarding future life,\nA man gives children to his wife.\nThis hermit's son, whom here you see\nA suppliant, refuge seeks with me.\nO sons, the friendless youth befriend,\nAnd, pleasing me, his life defend.\nFor holy works you all have wrought,\nTrue to the virtuous life I taught.\nGo, and as victims doomed to bleed,\nDie, and Lord Agni's hunger feed.\nSo shall the rite completed end,\nThis orphan gain a saving friend,\nDue offerings to the Gods be paid,\nAnd your own father's voice obeyed.\"",
            "Then Madhushyand and all the rest\nAnswered their sire with scorn and jest:\n\"What! aid to others' sons afford,\nAnd leave thine own to die, my lord!\nTo us it seems a horrid deed,\nAs 'twere on one's own flesh to feed.\"",
            "The hermit heard his sons' reply,\nAnd burning rage inflamed his eye.\nThen forth his words of fury burst:\n\"Audacious speech, by virtue cursed!\nIt lifts on end each shuddering hair—\nMy charge to scorn! my wrath to dare!\nYou, like Vaśishṭha's evil brood,\nShall make the flesh of dogs your food\nA thousand years in many a birth,\nAnd punished thus shall dwell on earth.\"",
            "Thus on his sons his curse he laid.\nThen calmed again that youth dismayed,\nAnd blessed him with his saving aid:\n\"When in the sacred fetters bound,\nAnd with a purple garland crowned,\nAt Vishṇu's post thou standest tied,\nWith lauds be Agni glorified.\nAnd these two hymns of holy praise\nForget not, Hermit's son, to raise\nIn the king's rite, and thou shalt be\nLord of thy wish, preserved, and free.\"",
            "He learnt the hymns with mind intent,\nAnd from the hermit's presence went.\nTo Ambarísha thus he spake:\n\"Let us our onward journey take.\nHaste to thy home, O King, nor stay\nThe lustral rites with slow delay.\"",
            "The boy's address the monarch cheered,\nAnd soon the sacred ground he neared.\nThe convocation's high decree\nDeclared the youth from blemish free;\nClothed in red raiment he was tied\nA victim at the pillar's side.\nThere bound, the Fire-God's hymn he raised,\nAnd Indra and Upendra praised.\nThousand-eyed Vishṇu, pleased to hear\nThe mystic laud, inclined his ear,\nAnd won by worship, swift to save,\nLong life to Śunahśepha gave.\nThe king in bounteous measure gained\nThe fruit of sacrifice ordained,\nBy grace of Him who rules the skies,\nLord Indra of the thousand eyes.",
            "And Viśvámitra evermore.\nPursued his task on Pushkar's shore\nUntil a thousand years had past\nIn fierce austerity and fast."
        ]
    },
    {
        "number": "LXIII",
        "title": "Menaká",
        "paragraphs": [
            "A thousand years had thus flown by\nWhen all the Gods within the sky,\nEager that he the fruit might gain\nOf fervent rite and holy pain,\nApproached the great ascetic, now\nBathed after toil and ended vow.\nThen Brahmá speaking for the rest\nWith sweetest words the sage addressed:\n\"Hail, Saint! This high and holy name\nThy rites have won, thy merits claim.\"",
            "Thus spoke the Lord whom Gods revere,\nAnd sought again his heavenly sphere.\nBut Viśvámitra, more intent,\nHis mind to sterner penance bent.\nSo many a season rolled away,\nWhen Menaká, fair nymph, one day\nCame down from Paradise to lave\nHer perfect limbs in Pushkar's wave,\nThe glorious son of Kuśik saw\nThat peerless shape without a flaw\nFlash through the flood's translucent shroud\nLike lightning gleaming through a cloud.\nHe saw her in that lone retreat,\nMost beautiful from head to feet,\nAnd by Kandarpa's might subdued\nHe thus addressed her as he viewed:\n\"Welcome, sweet nymph! O deign, I pray,\nIn these calm shades awhile to stay.\nTo me some gracious favour show,\nFor love has set my breast aglow.\"",
            "He spoke. The fairest of the fair\nMade for awhile her dwelling there,\nWhile day by day the wild delight\nStayed vow austere and fervent rite\nThere as the winsome charmer wove\nHer spells around him in the grove,\nAnd bound him in a golden chain,\nFive sweet years fled, and five again.\nThen Viśvámitra woke to shame,\nAnd, fraught with anguish, memory came\nFor quick he knew, with anger fired,\nThat all the Immortals had conspired\nTo lap his careless soul in ease,\nAnd mar his long austerities.\n\"Ten years have past, each day and night\nUnheeded in delusive flight.\nSo long my fervent rites were stayed,\nWhile thus I lay by love betrayed.\"\nAs thus long sighs the hermit heaved,\nAnd, touched with deep repentance, grieved,\nHe saw the fair one standing nigh\nWith suppliant hands and trembling eye.\nWith gentle words he bade her go,\nThen sought the northern hills of snow.\nWith firm resolve he vowed to beat\nThe might of love beneath his feet.\nStill northward to the distant side\nOf Kauśikí, the hermit hide,\nAnd gave his life to penance there\nWith rites austere most hard to bear.\nA thousand years went by, and still\nHe laboured on the northern hill\nWith pains so terrible and drear\nThat all the Gods were chilled with fear,\nAnd Gods and saints, for swift advice,\nMet in the halls of Paradise.\n\"Let Kuśik's son,\" they counselled, \"be\nA Mighty saint by just decree.\"\nHis ear to hear their counsel lent\nThe Sire of worlds, omnipotent.\nTo him enriched by rites severe\nHe spoke in accents sweet to hear:\n\"Hail, Mighty Saint! dear son, all hail!\nThy fervour wins, thy toils prevail.\nWon by thy vows and zeal intense\nI give this high preëminence.\"\nHe to the General Sire replied,\nNot sad, nor wholly satisfied:\n\"When thou, O Brahmá, shalt declare\nThe title, great beyond compare,\nOf Bráhman saint my worthy meed,\nHard earned by many a holy deed,\nThen may I deem in sooth I hold\nEach sense of body well controlled.\"\nThen Brahmá cried, \"Not yet, not yet:\nToil on awhile O Anchoret!\"",
            "Thus having said to heaven he went,\nThe saint, upon his task intent,\nBegan his labours to renew,\nWhich sterner yet and fiercer grew.\nHis arms upraised, without a rest,\nWith but one foot the earth he pressed;\nThe air his food, the hermit stood\nStill as a pillar hewn from wood.\nAround him in the summer days\nFive mighty fires combined to blaze.\nIn floods of rain no veil was spread\nSave clouds, to canopy his head.\nIn the dank dews both night and day\nCouched in the stream the hermit lay.\nThus, till a thousand years had fled,\nHe plied his task of penance dread.\nThen Vishṇu and the Gods with awe\nThe labours of the hermit saw,\nAnd Śakra, in his troubled breast,\nLord of the skies, his fear confessed.\nAnd brooded on a plan to spoil\nThe merits of the hermit's toil.\nEncompassed by his Gods of Storm\nHe summoned Rambhá, fair of form,\nAnd spoke a speech for woe and weal,\nThe saint to mar, the God to heal."
        ]
    },
    {
        "number": "LXIV",
        "title": "Rambhá",
        "paragraphs": [
            "\"A great emprise, O lovely maid,\nTo save the Gods, awaits thine aid:\nTo bind the son of Kuśik sure,\nAnd take his soul with love's sweet lure.\"\nThus order'd by the Thousand-eyed\nThe suppliant nymph in fear replied:\n\"O Lord of Gods, this mighty sage\nIs very fierce and swift to rage.\nI doubt not, he so dread and stern\nOn me his scorching wrath will turn.\nOf this, my lord, am I afraid:\nHave mercy on a timid maid.\"\nHer suppliant hands began to shake,\nWhen thus again Lord Indra spake:\n\"O Rambhá, drive thy fears away,\nAnd as I bid do thou obey.\nIn Koïl's form, who takes the heart\nWhen trees in spring to blossom start,\nI, with Kandarpa for my friend,\nClose to thy side mine aid will lend.\nDo thou thy beauteous splendour arm\nWith every grace and winsome charm,\nAnd from his awful rites seduce\nThis Kuśik's son, the stern recluse.\"",
            "Lord Indra ceased. The nymph obeyed:\nIn all her loveliest charms arrayed,\nWith winning ways and witching smile\nShe sought the hermit to beguile.\nThe sweet note of that tuneful bird\nThe saint with ravished bosom heard,\nAnd on his heart a rapture passed\nAs on the nymph a look he cast.\nBut when he heard the bird prolong\nHis sweet incomparable song,\nAnd saw the nymph with winning smile,\nThe hermit's heart perceived the wile.\nAnd straight he knew the Thousand-eyed\nA plot against his peace had tried.\nThen Kuśik's son indignant laid\nHis curse upon the heavenly maid:\n\"Because thou wouldst my soul engage\nWho fight to conquer love and rage,\nStand, till ten thousand years have flown,\nIll-fated maid, transformed to stone.\nA Bráhman then, in glory strong,\nMighty through penance stern and long,\nShall free thee from thine altered shape;\nThou from my curse shalt then escape.\"\nBut when the saint had cursed her so,\nHis breast was burnt with fires of woe,\nGrieved that long effort to restrain\nHis mighty wrath was all in vain.\nCursed by the angry sage's power,\nShe stood in stone that selfsame hour.\nKandarpa heard the words he said,\nAnd quickly from his presence fled.\nHis fall beneath his passion's sway\nHad reft the hermit's meed away.\nUnconquered yet his secret foes,\nThe humbled saint refused repose:\n\"No more shall rage my bosom till,\nSealed be my lips, my tongue be still.\nMy very breath henceforth I hold\nUntil a thousand years are told:\nVictorious o'er each erring sense,\nI'll dry my frame with abstinence,\nUntil by penance duly done\nA Bráhman's rank be bought and won.\nFor countless years, as still as death,\nI taste no food, I draw no breath,\nAnd as I toil my frame shall stand\nUnharmed by time's destroying hand.\""
        ]
    },
    {
        "number": "LXV",
        "title": "Visvámitra's Triumph",
        "paragraphs": [
            "Then from Himálaya's heights of snow,\nThe glorious saint prepared to go,\nAnd dwelling in the distant east\nHis penance and his toil increased.\nA thousand years his lips he held\nClosed by a vow unparalleled,\nAnd other marvels passing thought,\nUnrivalled in the world, he wrought.\nIn all the thousand years his frame\nDry as a log of wood became.\nBy many a cross and check beset,\nRage had not stormed his bosom yet.\nWith iron will that naught could bend\nHe plied his labour till the end.\nSo when the weary years were o'er,\nFreed from his vow so stern and sore,\nThe hermit, all his penance sped,\nSate down to eat his meal of bread.\nThen Indra, clad in Bráhman guise,\nAsked him for food with hungry eyes.\nThe mighty saint, with steadfast soul,\nTo the false Bráhman gave the whole,\nAnd when no scrap for him remained,\nFasting and faint, from speech refrained.\nHis silent vow he would not break:\nNo breath he heaved, no word he spake,\nThen as he checked his breath, behold!\nAround his brow thick smoke-clouds rolled\nAnd the three worlds, as if o'erspread\nWith ravening flames, were filled with dread.\nThen God and saint and bard, convened,\nAnd Nága lord, and snake, and fiend,\nThus to the General Father cried,\nDistracted, sad, and terrified:\n\"Against the hermit, sore assailed,\nLure, scathe, and scorn have naught availed,\nProof against rage and treacherous art\nHe keeps his vow with constant heart.\nNow if his toils assist him naught\nTo gain the boon his soul has sought,\nHe through the worlds will ruin send\nThat fixt and moving things shall end,\nThe regions now are dark with doom,\nNo friendly ray relieves the gloom.\nEach ocean foams with maddened tide,\nThe shrinking hills in fear subside.\nTrembles the earth with feverous throe\nThe wind in fitful tempest blows.\nNo cure we see with troubled eyes:\nAnd atheist brood on earth may rise.\nThe triple world is wild with care,\nOr spiritless in dull despair.\nBefore that saint the sun is dim,\nHis blessed light eclipsed by him.\nNow ere the saint resolve to bring\nDestruction on each living thing,\nLet us appease, while yet we may,\nHim bright as fire, like fire to slay.\nYea, as the fiery flood of Fate\nLays all creation desolate,\nHe o'er the conquered Gods may reign:\nO, grant him what he longs to gain.\"",
            "Then all the Blest, by Brahmá led,\nApproached the saint and sweetly said:\n\"Hail, Bráhman Saint! for such thy place:\nThy vows austere have won our grace.\nA Bráhman's rank thy penance stern\nAnd ceaseless labour richly earn.\nI with the Gods of Storm decree\nLong life, O Bráhman Saint, to thee.\nMay peace and joy thy soul possess:\nGo where thou wilt in happiness.\"",
            "Thus by the General Sire addressed,\nJoy and high triumph filled his breast.\nHis head in adoration bowed,\nThus spoke he to the Immortal crowd:\n\"If I, ye Gods, have gained at last\nBoth length of days and Bráhman caste,\nGrant that the high mysterious name,\nAnd holy Vedas, own my claim,\nAnd that the formula to bless\nThe sacrifice, its lord confess.\nAnd let Vaśishṭha, who excels\nIn Warriors' art and mystic spells,\nIn love of God without a peer,\nConfirm the boon you promise here.\"",
            "With Brahmá's son Vaśishṭha, best\nOf those who pray with voice repressed,\nThe Gods by earnest prayer prevailed,\nAnd thus his new-made friend he hailed:\n\"Thy title now is sure and good\nTo rights of saintly Bráhmanhood.\"\nThus spake the sage. The Gods, content,\nBack to their heavenly mansions went.\nAnd Viśvámitra, pious-souled,\nAmong the Bráhman saints enrolled,\nOn reverend Vaśishṭha pressed\nThe honours due to holy guest.\nSuccessful in his high pursuit,\nThe sage, in penance resolute,\nWalked in his pilgrim wanderings o'er\nThe whole broad land from shore to shore.\n'Twas thus the saint, O Raghu's son,\nHis rank among the Bráhmans won.\nBest of all hermits, Prince, is he;\nIn him incarnate Penance see.\nFriend of the right, who shrinks from ill,\nHeroic powers attend him still.\"",
            "The Bráhman, versed in ancient lore,\nThus closed his tale, and said no more,\nTo Śatánanda Kuśik's son\nCried in delight, Well done! well done!\nThen Janak, at the tale amazed,\nSpoke thus with suppliant hands upraised:\n\"High fate is mine, O Sage, I deem,\nAnd thanks I owe for bliss supreme,\nThat thou and Raghu's children too\nHave come my sacrifice to view.\nTo look on thee with blessed eyes\nExalts my soul and purifies.\nYea, thus to see thee face to face\nEnriches me with store of grace.\nThy holy labours wrought of old,\nAnd mighty penance, fully told,\nRáma and I with great delight\nHave heard, O glorious Anchorite.\nUnrivalled thine ascetic deeds:\nThy might, O Saint, all might exceeds.\nNo thought may scan, no limit bound\nThe virtues that in thee are found.\nThe story of thy wondrous fate\nMy thirsty ears can never sate.\nThe hour of evening rites is near:\nThe sun declines in swift career.\nAt early dawn, O Hermit, deign\nTo let me see thy face again.\nBest of ascetics, part in bliss:\nDo thou thy servant now dismiss.\"",
            "The saint approved, and glad and kind\nDismissed the king with joyful mind\nAround the sage King Janak went\nWith priests and kinsmen reverent.\nThen Viśvámitra, honoured so,\nBy those high-minded, rose to go,\nAnd with the princes took his way\nTo seek the lodging where they lay."
        ]
    },
    {
        "number": "LXVI",
        "title": "Janak's Speech",
        "paragraphs": [
            "With cloudless lustre rose the sun;\nThe king, his morning worship done,\nOrdered his heralds to invite\nThe princes and the anchorite.\nWith honour, as the laws decree,\nThe monarch entertained the three.\nThen to the youths and saintly man\nVideha's lord this speech began:\n\"O blameless Saint, most welcome thou!\nIf I may please thee tell me how.\nSpeak, mighty lord, whom all revere,\n'Tis thine to order, mine to hear.\"",
            "Thus he on mighty thoughts intent;\nThen thus the sage most eloquent:\n\"King Daśaratha's sons, this pair\nOf warriors famous everywhere,\nAre come that best of bows to see\nThat lies a treasure stored by thee.\nThis, mighty Janak, deign to show,\nThat they may look upon the bow,\nAnd then, contented, homeward go.\"",
            "Then royal Janak spoke in turn:\n\"O best of Saints, the story learn\nWhy this famed bow, a noble prize,\nA treasure in my palace lies.\nA monarch, Devarát by name,\nWho sixth from ancient Nimi came,\nHeld it as ruler of the land,\nA pledge in his successive hand.\nThis bow the mighty Rudra bore\nAt Daksha's sacrifice of yore,\nWhen carnage of the Immortals stained\nThe rite that Daksha had ordained.\nThen as the Gods sore wounded fled,\nVictorious Rudra, mocking, said:\n\"Because, O Gods, ye gave me naught\nWhen I my rightful portion sought,\nYour dearest parts I will not spare,\nBut with my bow your frames will tear.\"",
            "The Sons of Heaven, in wild alarm,\nSoft flatteries tried his rage to charm.\nThen Bhava, Lord whom Gods adore,\nGrew kind and friendly as before,\nAnd every torn and mangled limb\nWas safe and sound restored by him.\nThenceforth this bow, the gem of bows,\nThat freed the God of Gods from foes,\nStored by our great forefathers lay\nA treasure and a pride for aye.\nOnce, as it chanced, I ploughed the ground,\nWhen sudden, 'neath the share was found\nAn infant springing from the earth,\nNamed Sítá from her secret birth.\nIn strength and grace the maiden grew,\nMy cherished daughter, fair to view.\nI vowed her, of no mortal birth,\nMeet prize for noblest hero's worth.\nIn strength and grace the maiden grew,\nAnd many a monarch came to woo.\nTo all the princely suitors I\nGave, mighty Saint, the same reply:\n\"I give not thus my daughter, she\nPrize of heroic worth shall be.\nTo Míthilá the suitors pressed\nTheir power and might to manifest.\nTo all who came with hearts aglow\nI offered Śiva's wondrous bow.\nNot one of all the royal band\nCould raise or take the bow in hand.\nThe suitors' puny might I spurned,\nAnd back the feeble princes turned.\nEnraged thereat, the warriors met,\nWith force combined my town beset.\nStung to the heart with scorn and shame,\nWith war and threats they madly came,\nBesieged my peaceful walls, and long\nTo Míthilá did grievous wrong.\nThere, wasting all, a year they lay,\nAnd brought my treasures to decay,\nFilling my soul, O Hermit chief,\nWith bitter woe and hopeless grief.\nAt last by long-wrought penance I\nWon favour with the Gods on high,\nWho with my labours well content\nA four-fold host to aid me sent.\nThen swift the baffled heroes fled\nTo all the winds discomfited—\nWrong-doers, with their lords and host,\nAnd all their valour's idle boast.\nThis heavenly bow, exceeding bright,\nThese youths shall see, O Anchorite.\nThen if young Ráma's hand can string\nThe bow that baffled lord and king,\nTo him I give, as I have sworn,\nMy Sítá, not of woman born.\""
        ]
    }
]

# Translate each canto
result = []
for canto in cantos:
    print(f"Translating Canto {canto['number']}: {canto['title']}...", file=sys.stderr)

    paras_he = translate_paragraphs(
        client,
        canto['paragraphs'],
        'I',
        canto['number'],
        canto['title']
    )

    canto_he = {
        "number": canto['number'],
        "title": canto['title'],
        "paragraphs": paras_he
    }
    result.append(canto_he)
    print(f"  ✓ {len(paras_he)} paragraphs", file=sys.stderr)

# Output only JSON
print(json.dumps(result, ensure_ascii=False, indent=2))
